name: Build Dependency Packages

on:
  workflow_dispatch:
    inputs:
        bundlename:
          type: string
          description: The name of the Ayon-bundle to make dependency package for.
          required: true
        python_version:
          type: string
          default: 3.9.6
          description: The version of Python to use for building.
          required: true


env:
  AYON_SERVER_URL: ${{secrets.AYON_SERVER_URL}}
  AYON_API_KEY: ${{secrets.AYON_API_KEY}}

jobs:
  build-win:
      runs-on: windows-latest
      steps:
        - name: Install PyEnv
          run: |
            Set-ExecutionPolicy unrestricted
            Invoke-WebRequest -UseBasicParsing -Uri "https://raw.githubusercontent.com/pyenv-win/pyenv-win/master/pyenv-win/install-pyenv-win.ps1" -OutFile "./install-pyenv-win.ps1"; &"./install-pyenv-win.ps1"
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: TEMP - Remove poetry.lock file
          run: rm poetry.lock
        - name: Install Python
          run: |
            pyenv install 3.9.6
            pyenv global 3.9.6
            pyenv local 3.9.6
        - name: Run Ayon-Dependency-Tool
          run: |
            PowerShell -ExecutionPolicy Bypass
            Set-ExecutionPolicy -ExecutionPolicy unrestricted -Scope LocalMachine
            mkdir build_win
            ./start.ps1 install
            ./start.ps1 create -b ${{github.event.inputs.bundlename}} --server ${{secrets.AYON_SERVER_URL}} --api-key ${{secrets.AYON_API_KEY}} --output-dir ./build_win
            cd build_win
            ls

          shell: pwsh
