name: Build Dependency Packages

on:
  workflow_dispatch:
    inputs:
        bundlename:
          type: string
          description: The name of the Ayon-bundle to make dependency package for.
          required: true
        python_version:
          type: string
          default: 3.9.6
          description: The version of Python to use for building.
          required: true


env:
  AYON_SERVER_URL: ${{secrets.AYON_SERVER_URL}}
  AYON_API_KEY: ${{secrets.AYON_API_KEY}}


jobs:
  build-win:
      runs-on: windows-latest
      strategy:
        matrix:
          python:
            - 3.9.6
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: TEMP - Remove poetry.lock file
          run: rm poetry.lock
        - name: Install python version
          uses: gabrielfalcao/pyenv-action@v18
          with:
            default: "${{ matrix.python }}"
            command: pip install -U pip  # upgrade pip after installing python
        - name: Run Ayon-Dependency-Tool
          run: |
            Set-ExecutionPolicy -ExecutionPolicy unrestricted -Scope LocalMachine
            mkdir build_win
            ./start.ps1 install
            ./start.ps1 create -b ${{github.event.inputs.bundlename}} --output-dir ./build_win
            cd build_win
            ls
          shell: pwsh
