name: Build Dependency Packages

on:
  workflow_dispatch:
    inputs:
        bundlename:
          type: string
          description: The name of the Ayon-bundle to make dependency package for.
          required: true
        python_version:
          type: string
          default: 3.9.6
          description: The version of Python to use for building.
          required: true


env:
  AYON_SERVER_URL: ${{secrets.AYON_SERVER_URL}}
  AYON_API_KEY: ${{secrets.AYON_API_KEY}}


jobs:
  build-win:
      runs-on: windows-latest
      steps:
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.9.6'
        - name: setup pyenv
          id: pyenv_installation
          uses: "gabrielfalcao/pyenv-action@v18"
        - name: debug pyenv
          run: |
            echo ${{ steps.pyenv_installation.outputs.pyenv_root }}
            pyenv which python
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: TEMP - Remove poetry.lock file
          run: rm poetry.lock
        - name: Run Ayon-Dependency-Tool
          run: |
            pyenv global 3.9.6
            pyenv local 3.9.6
            Set-ExecutionPolicy -ExecutionPolicy unrestricted -Scope LocalMachine
            mkdir build_win
            ./start.ps1 install
            ./start.ps1 create -b ${{github.event.inputs.bundlename}} --output-dir ./build_win
            cd build_win
            ls
          shell: pwsh
